@extends('layouts.admin')
@section('content')
    <div class="row margin-top-20">
        <div class="col-xs-12">
            <h2>Restrições de Uso</h2>
            <p>O visitante poderá usar este sítio virtual apenas para finalidades lícitas, conforme as legislações do país, estado e cidade de acesso. Este espaço não poderá ser utilizado para publicar, enviar, distribuir ou divulgar conteúdos ou informação de caráter difamatório, obsceno ou ilícito, inclusive informações de propriedade exclusiva pertencentes a outras pessoas ou empresas sem a expressa autorização do detentor desses direitos.</p>
            <h2>Limitação da Responsabilidade</h2>
            <p>Os materiais são fornecidos neste sítio virtual sem nenhuma garantia explícita ou implícita de comercialização ou adequação a qualquer objetivo específico. Em nenhum caso o C3 Projetos ou os seus colaboradores serão responsabilizados por quaisquer danos, incluindo lucros cessantes, interrupção de negócio, ou perda de informação que resultem do uso ou da incapacidade de usar os materiais. O C3 Projetos não garante a precisão ou integridade das informações, textos, gráficos, imagens, links e outros itens dos materiais.</p>
            <p>O C3 Projetos não se responsabiliza pelo conteúdo dos artigos e informações aqui publicadas, uma vez que os textos são de autoria de terceiros e não traduzem, necessariamente, a opinião do sítio virtual.</p>
            <p>O C3 Projetos tampouco é responsável pela violação de direitos autorais decorrente de informações, documentos e materiais publicados neste sítio virtual, compromentendo-se a retirá-los do ar assim que notificado da infração.</p>
            <h2>Informações Enviadas pelos Usuários e Colaboradores</h2>
            <p>Qualquer material, informação, artigos ou outras comunicações que forem transmitidas, enviadas ou publicadas neste sítio virtual, serão considerados informação não confidencial, e qualquer violação aos direitos dos seus criadores não será de responsabilidade do C3 Projetos. É terminantemente proibido transmitir, trocar ou publicar, através deste sítio virtual, qualquer material de cunho obsceno, difamatório ou ilegal, bem como textos ou criações de terceiros sem a autorização do autor. O C3 Projetos reserva-se o direito de restringir o acesso às informações enviadas por terceiros aos seus usuários.</p>            
            <p>O C3 Projetos poderá, mas não é obrigado, a monitorar, revistar e restringir o acesso a qualquer área no sítio virtual onde usuários transmitem e trocam informações entre si, incluindo, mas não limitado a, dispositivos e salas de chat, centro de mensagens ou outros fóruns de debates, podendo retirar do ar ou restringir o acesso a qualquer uma destas informações ou comunicações. Porém, o C3 Projetos não é responsável pelo conteúdo de qualquer uma das informações trocadas entre os usuários, sejam elas lícitas ou ilícitas.</p>
            <h2>Links para Sítios Virtuais de Terceiros</h2>
            <p>Os sítios virtuais apontados não estão sob o controle do C3 Projetos, que não é responsável pelo conteúdo de qualquer outro sítio virtual indicado ou acessado por meio do C3 Projetos. O C3 Projetos reserva-se o direito de eliminar qualquer link ou direcionamento a outros sítios virtuais ou serviços a qualquer momento. O C3 Projetos não endossa firmas ou produtos indicados, acessados ou divulgados através deste sítio virtual, tampouco pelos anúncios aqui publicados, reservando-se ao direito de publicar este alerta em suas páginas eletrônicas sempre que considerar necessário.</p>
            <h2>Direitos Autorais e Propriedade Intelectual</h2>
            <p>Os documentos, conteúdos e criações contidos neste sítio virtual pertencem aos seus criadores e colaboradores. O C3 Projetos empenha-se mas não é obrigado a fornecer as ferramentas e funcionalidades que auxiliem os utilizadores na elaboração dos relatórios e consulta e indicação de conteúdos relacionados ao seu projeto. A autoria dos conteúdo, material e imagens exibidos no C3 Projetos são protegida por leis nacionais e internacionais. Não podem ser copiados, reproduzidos, modificados, publicados, atualizados, postados, transmitidos ou distribuídos de qualquer maneira sem autorização prévia e por escrito dos respectivos autores, sejam eles o C3 Projetos ou seus usuários.</p>
            <p>As imagens contidas neste sítio virtual são aqui incorporadas apenas para fins de visualização, e, salvo autorização expressa por escrito dos autores, não podem ser gravadas ou baixadas via download. A reprodução ou armazenamento de materiais recuperados a partir deste serviço sujeitará os infratores às penas da lei. O nome do sítio virtual ( C3 Projetos) , sua assinatura visual (logotipo e símbolo), o nome de domínio para acesso na Internet (www.projetoemacao.com), bem como todos os elementos característicos da tecnologia desenvolvida e aqui apresentada, sob a forma da articulação de bases de dados, constituem marcas registradas e propriedades intelectuais privadas e todos os direitos decorrentes de seu registro são assegurados por lei. Alguns direitos de uso podem ser cedidos pelo C3 Projetos, em contrato ou licença especial, que pode ser cancelada a qualquer momento se não cumpridos os seus termos.</p>
            <p>As marcas registradas do C3 Projetos só podem ser usadas publicamente com autorização expressa. O uso destas marcas registradas em publicidade e promoção de produtos deve ser adequadamente informado.</p>
            <p>O sítio virtual do C3 Projetos empenha-se mas não é obrigado a automatizar ou verificar as fontes dos conteúdos inseridos por seus usuários, cabendo ao usuário a verificação e indicação das respectivas fontes dos conteúdos utilizados, quando de terceiros.</p>
        </div>
    </div>
@endsection